defaults:
  - backbone: masked_croco_multi

name: nas3r-m

opacity_mapping:
  initial: 0.0
  final: 0.0
  warm_up: 1

num_monocular_samples: 32
num_surfaces: 1
predict_opacity: false

gaussians_per_pixel: 1

gaussian_adapter:
  gaussian_scale_min: 0.5
  gaussian_scale_max: 15.0
  sh_degree: 4

d_feature: 128

visualizer:
  num_samples: 8
  min_resolution: 256
  export_ply: false

apply_bounds_shim: true

gs_params_head_type: dpt_gs
pose_free: true
pretrained_weights: ""

pose_make_baseline_1: false
pose_make_relative: true
pose_head_type: mlp


estimating_focal: false
estimating_pose: true


pose_head:
  pose_init_t: false
  use_homogeneous: false
  concat_enc: false
  estimate_focal: true


depth_activation: 'sigmoid'

equal_fxfy: true
equal_view_intrinsics: true

gd_cross_attn:
  enabled: true
  gaussian_feat_dim: 256
  cond_dim: 8
  hidden_dim: 160
  num_heads: 16

freeze_original_lr_network: true
trainable_new_modules:
  - gd_cross_attn
  - resplat_pt
  - gaussian_child_decoder
  - hisplat_sr_feature_extractor

resplat_pt:
  enabled: true
  channels: 512
  knn_samples: 16
  num_blocks: 4
  attn_proj_channels: 64
  input_dim: null

gaussian_child_decoder:
  enabled: true
  input_dim: 512
  hidden_dim: 512
  child_feat_dim: 320
  num_children: 8
  n_frequencies: 15
  scale_min: 1.0e-6
  scale_init_divisor: 2.0
  offset_residual_bound: 0.5
  num_rings: null
  max_radius_pixel: 0.95

swinir_weight_path: /space0/mengxl/NAS3R-master/pretrained_weights/001_classicalSR_DF2K_s64w8_SwinIR-M_x4.pth
swinir_upscale: 4
swinir_img_size: 64
swinir_window_size: 8

hisplat_sr_features:
  enabled: true
  resunet_dims: [32, 64, 128]
  croco_dim: 1024
  out_dim_64: 128
  out_dim_256: 64
